services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: chatdev_backend
    env_file:
      - .env
      - .env.docker
    expose:
      - "6400"
    restart: unless-stopped
    networks:
      - appnet
    # Optional healthcheck (adjust path if different)
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://localhost:6400/api/health || exit 1"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    container_name: chatdev_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - appnet
    # Optional healthcheck
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -q -O - http://localhost/ >/dev/null 2>&1 || exit 1"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5

networks:
  appnet: {}
