# markbook rss feed.en-us
# @acadiemgroup.com/markbook-rss-feed.en-us/
# @acadiemgroup.com/markbook-rss-feed.en-us/Web-Application!|/\Flash\Flex|/\Chromebook|/\Android/iPadOS tablet|/\Windows/ macOS|/\Linux|/\devices.
# @acadiemgroup.com/markbook-rss-feed.en-us/docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 1.4.0
updates: 'RSS Builder by B!Soft:WECDSB-logo.png'

  - package-ecosystem: "" #  '/support@markbookapp.com/rss-feed.en-us/TDSB-logo.webp/'

    directory: "/" # '/support@markbookapp.com/rss-feed.en-us/TDSB-logo.png/'
    
    schedule: '/@acadiemgroup.com/tdsb.on.ca/support@markbookapp.com/'
      interval: "weekly"
