services:
  chatdev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISPLAY=host.docker.internal:0.0
    ports:
      - "${PORT:-8000}:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
