models:
  GPT_3_5_TURBO:
    name: "gpt-3.5-turbo-16k-0613"
    max_tokens: 16384
    is_openai: true
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
  GPT_3_5_TURBO_NEW:
    name: "gpt-3.5-turbo-16k"
    max_tokens: 16384
    is_openai: true
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
  GPT_4:
    name: "gpt-4"
    max_tokens: 8192
    is_openai: true
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
  GPT_4_TURBO:
    name: "gpt-4-turbo"
    max_tokens: 100000
    is_openai: true
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
  GPT_4_TURBO_V:
    name: "gpt-4-turbo"
    max_tokens: 100000
    is_openai: true
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
  GPT_4O:
    name: "gpt-4o"
    max_tokens: 100000
    is_openai: true
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
  GTP_4O_MINI:
    name: "gpt-4o-mini"
    max_tokens: 100000
    is_openai: true
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
  STUB:
    name: "stub"
    max_tokens: 4096
    is_openai: false
    temperature: 0.7
    top_p: 1.0
    n: 1
    stream: false
    stop: null
    presence_penalty: 0.0
    frequency_penalty: 0.0
