models:
  GPT_3_5_TURBO:
    name: "gpt-3.5-turbo-16k-0613"
    max_tokens: 16384
  GPT_3_5_TURBO_NEW:
    name: "gpt-3.5-turbo-16k"
    max_tokens: 16384
  GPT_4:
    name: "gpt-4"
    max_tokens: 8192
  GPT_4_32K:
    name: "gpt-4-32k"
    max_tokens: 32768
  GPT_4_TURBO:
    name: "gpt-4-turbo"
    max_tokens: 100000
  GPT_4_TURBO_V:
    name: "gpt-4-turbo"
    max_tokens: 100000
  GPT_4O:
    name: "gpt-4o"
    max_tokens: 100000
  GTP_4O_MINI:
    name: "gpt-4o-mini"
    max_tokens: 100000
  STUB:
    name: "stub"
    max_tokens: 4096
    is_openai: false
