default_config: &default_config
  temperature: 0.7
  top_p: 1.0
  n: 1
  stream: false
  stop: null
  presence_penalty: 0.0
  frequency_penalty: 0.0
  is_openai: true
  max_tokens: 4096
  base_url: https://api.openai.com/v1/ 

models:
  GPT_3_5_TURBO:
    <<: *default_config
    name: "gpt-3.5-turbo-16k-0613"
    max_tokens: 16384

  GPT_3_5_TURBO_NEW:
    <<: *default_config
    name: "gpt-3.5-turbo-16k"
    max_tokens: 16384

  GPT_4:
    <<: *default_config
    name: "gpt-4"
    max_tokens: 8192

  GPT_4_32K:
    <<: *default_config
    name: "gpt-4-32k"
    max_tokens: 32768

  GPT_4_TURBO:
    <<: *default_config
    name: "gpt-4-turbo"
    max_tokens: 100000

  GPT_4_TURBO_V:
    <<: *default_config
    name: "gpt-4-turbo"
    max_tokens: 100000

  GPT_4O:
    <<: *default_config
    name: "gpt-4o"
    max_tokens: 100000

  GTP_4O_MINI:
    <<: *default_config
    name: "gpt-4o-mini"
    max_tokens: 100000

  STUB:
    <<: *default_config
    name: "stub"
    max_tokens: 4096
    is_openai: false

  LLAMA_3:
    <<: *default_config
    name: "llama-3.1-70b-versatile"
    max_tokens: 100000
    is_openai: false
    base_url: https://api.groq.com/openai/v1 