background_prompt: Startr.Team is a software company powered by multiple intelligent
  agents, such as chief executive officer, chief human resources officer, chief product
  officer, chief technology officer, etc, with a multi-agent organizational structure
  and the mission of 'changing the digital world through programming'.
chain:
- max_turn_step: -1
  need_reflect: 'True'
  phase: DemandAnalysis
  phaseType: SimplePhase
- max_turn_step: -1
  need_reflect: 'True'
  phase: ChooseLanguage
  phaseType: SimplePhase
- max_turn_step: 1
  need_reflect: 'False'
  phase: Coding
  phaseType: SimplePhase
- Composition:
  - max_turn_step: 1
    need_reflect: 'False'
    phase: CodeThis
    phaseType: SimplePhase
  cycleNum: 10
  phase: CodeThisProject
  phaseType: ComposedPhase
- Composition:
  - max_turn_step: 1
    need_reflect: 'False'
    phase: CodeReviewComment
    phaseType: SimplePhase
  - max_turn_step: 1
    need_reflect: 'False'
    phase: CodeReviewModification
    phaseType: SimplePhase
  cycleNum: 3
  phase: CodeReview
  phaseType: ComposedPhase
- Composition:
  - max_turn_step: 1
    need_reflect: 'False'
    phase: CodeReviewHuman
    phaseType: SimplePhase
  cycleNum: 5
  phase: HumanAgentInteraction
  phaseType: ComposedPhase
- Composition:
  - max_turn_step: 1
    need_reflect: 'False'
    phase: TestErrorSummary
    phaseType: SimplePhase
  - max_turn_step: 1
    need_reflect: 'False'
    phase: TestModification
    phaseType: SimplePhase
  cycleNum: 3
  phase: Test
  phaseType: ComposedPhase
- max_turn_step: 1
  need_reflect: 'True'
  phase: EnvironmentDescription
  phaseType: SimplePhase
- max_turn_step: 1
  need_reflect: 'False'
  phase: Manual
  phaseType: SimplePhase
clear_structure: 'True'
git_management: 'False'
gui_design: 'True'
incremental_develop: 'False'
recruits:
- Chief Executive Officer
- Counselor
- Chief Human Resource Officer
- Chief Product Officer
- Chief Technology Officer
- Programmer
- Code Reviewer
- Software Test Engineer
- Chief Creative Officer
self_improve: 'False'
web_spider: 'False'
with_memory: 'False'
